name: Publish To NPM
on:
  push:
    tags: 'v**'

jobs:
  publish:
    runs-on: ubuntu-latest
    name: 'publish to npm'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check current branch
        run: |
          branch=$(git branch -r --contains ${{ github.ref }})
          echo "::set-output name=branch::$branch"
          echo "branch=$branch" >> "$GITHUB_ENV"
          echo "Branch is $branch." 

      - name: Exit if not on main branch
        if: ${{endsWith(env.branch, 'main') == false}}
        run: exit -1

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: rm -rf node_modules && yarn install --frozen-lockfile
      - run: yarn build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
